// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnyOpe__-R2Xg1u2AjZQRnkX_gJN9n-TE',
    appId: '1:472845013892:web:af29c0e95944347b8d43d1',
    messagingSenderId: '472845013892',
    projectId: 'with-platform-ccc06',
    authDomain: 'with-platform-ccc06.firebaseapp.com',
    storageBucket: 'with-platform-ccc06.firebasestorage.app',
    measurementId: 'G-BH66PQ4XSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn7Vv0lvBGotmNMDcazqvSvIPT2ND1RPE',
    appId: '1:472845013892:android:79b402a357c2faaa8d43d1',
    messagingSenderId: '472845013892',
    projectId: 'with-platform-ccc06',
    storageBucket: 'with-platform-ccc06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpWAqjfyrz4hYMurLktk6r1WE3-harSc',
    appId: '1:472845013892:ios:9f00780ea8df2f698d43d1',
    messagingSenderId: '472845013892',
    projectId: 'with-platform-ccc06',
    storageBucket: 'with-platform-ccc06.firebasestorage.app',
    iosBundleId: 'com.example.withPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpWAqjfyrz4hYMurLktk6r1WE3-harSc',
    appId: '1:472845013892:ios:9f00780ea8df2f698d43d1',
    messagingSenderId: '472845013892',
    projectId: 'with-platform-ccc06',
    storageBucket: 'with-platform-ccc06.firebasestorage.app',
    iosBundleId: 'com.example.withPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnyOpe__-R2Xg1u2AjZQRnkX_gJN9n-TE',
    appId: '1:472845013892:web:5872cd1708bc0ae38d43d1',
    messagingSenderId: '472845013892',
    projectId: 'with-platform-ccc06',
    authDomain: 'with-platform-ccc06.firebaseapp.com',
    storageBucket: 'with-platform-ccc06.firebasestorage.app',
    measurementId: 'G-246SZQS0L1',
  );
}
